-- SCRIPT PRACT 3
-- 1. VISTAS DE OCUPACIÓN

-- V_OCUPACION_ASIGNADA

CREATE OR REPLACE VIEW V_OCUPACION_ASIGNADA AS
SELECT 
    s.CODIGO                 AS SEDE_CODIGO,
    s.NOMBRE                 AS SEDE_NOMBRE,
    a.EXAMEN_AULA_CODIGO     AS AULA_CODIGO,
    a.EXAMEN_FECHAYHORA      AS FECHA_EXAMEN,
    COUNT(a.ESTUDIANTE_DNI)  AS NUM_ESTUDIANTES
FROM SEDE s
JOIN ASISTENCIA a ON a.EXAMEN_SEDE_CODIGO = s.CODIGO
GROUP BY 
    s.CODIGO,
    s.NOMBRE,
    a.EXAMEN_AULA_CODIGO,
    a.EXAMEN_FECHAYHORA;

-- V_OCUPACION

CREATE OR REPLACE VIEW V_OCUPACION AS
SELECT 
    s.CODIGO                 AS SEDE_CODIGO,
    s.NOMBRE                 AS SEDE_NOMBRE,
    a.EXAMEN_AULA_CODIGO     AS AULA_CODIGO,
    a.EXAMEN_FECHAYHORA      AS FECHA_EXAMEN,
    COUNT(a.ESTUDIANTE_DNI)  AS NUM_ESTUDIANTES
FROM SEDE s
JOIN ASISTENCIA a ON a.EXAMEN_SEDE_CODIGO = s.CODIGO
WHERE a.ASISTE = 'S'
GROUP BY 
    s.CODIGO,
    s.NOMBRE,
    a.EXAMEN_AULA_CODIGO,
    a.EXAMEN_FECHAYHORA;

-- V_VIGILANTES

CREATE OR REPLACE VIEW V_VIGILANTES AS
SELECT 
    s.CODIGO                 AS SEDE_CODIGO,
    s.NOMBRE                 AS SEDE_NOMBRE,
    v.EXAMEN_AULA_CODIGO     AS AULA_CODIGO,
    v.EXAMEN_FECHAYHORA      AS FECHA_EXAMEN,
    COUNT(v.VOCAL_DNI)       AS NUM_VIGILANTES
FROM SEDE s
JOIN VIGILA v ON v.EXAMEN_SEDE_CODIGO = s.CODIGO
GROUP BY 
    s.CODIGO,
    s.NOMBRE,
    v.EXAMEN_AULA_CODIGO,
    v.EXAMEN_FECHAYHORA;

-- 2 PAQUETE PK_OCUPACION
-- OCUPACION_MAXIMA

-- CABECERA
CREATE OR REPLACE PACKAGE PK_OCUPACION AS
    FUNCTION OCUPACION_MAXIMA(P_SEDE NUMBER, P_AULA NUMBER) RETURN NUMBER;
    FUNCTION OCUPACION_OK RETURN BOOLEAN;
    FUNCTION VOCAL_DUPLICADO(P_VOCAL_DNI VARCHAR2) RETURN BOOLEAN;
    FUNCTION VOCALES_DUPLICADOS RETURN BOOLEAN;
    FUNCTION VOCAL_RATIO(P_RATIO NUMBER) RETURN BOOLEAN;
END PK_OCUPACION;
/

-- CUERPO
CREATE OR REPLACE PACKAGE BODY PK_OCUPACION AS

    FUNCTION OCUPACION_MAXIMA(P_SEDE NUMBER, P_AULA NUMBER) RETURN NUMBER AS
        V_RESULTADO NUMBER;
    BEGIN
        SELECT MAX(ALUMNOS + VOCALES)
        INTO V_RESULTADO
        FROM (
            SELECT
                COUNT(a.ESTUDIANTE_DNI) AS ALUMNOS,
                COUNT(v.VOCAL_DNI)      AS VOCALES
            FROM ASISTENCIA a
            LEFT JOIN VIGILA v
                ON  v.EXAMEN_FECHAYHORA  = a.EXAMEN_FECHAYHORA
                AND v.EXAMEN_AULA_CODIGO = a.EXAMEN_AULA_CODIGO
                AND v.EXAMEN_SEDE_CODIGO = a.EXAMEN_SEDE_CODIGO
            WHERE a.EXAMEN_SEDE_CODIGO = P_SEDE
              AND a.EXAMEN_AULA_CODIGO = P_AULA
              AND a.ASISTE = 'S'
            GROUP BY a.EXAMEN_FECHAYHORA
        );
        RETURN NVL(V_RESULTADO, 0);
    END OCUPACION_MAXIMA;

    FUNCTION OCUPACION_OK RETURN BOOLEAN AS
        V_CONTADOR NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_CONTADOR
        FROM EXAMEN e
        JOIN AULA au ON au.CODIGO = e.AULA_CODIGO 
                    AND au.SEDE_CODIGO = e.AULA_SEDE_CODIGO
        WHERE e.FECHAYHORA > SYSDATE
          AND (
              (SELECT COUNT(*) FROM ASISTENCIA a
               WHERE a.EXAMEN_FECHAYHORA  = e.FECHAYHORA
                 AND a.EXAMEN_AULA_CODIGO = e.AULA_CODIGO
                 AND a.EXAMEN_SEDE_CODIGO = e.AULA_SEDE_CODIGO
              ) > au.CAPACIDAD_EXAMEN
              OR
              (SELECT COUNT(*) FROM ASISTENCIA a
               WHERE a.EXAMEN_FECHAYHORA  = e.FECHAYHORA
                 AND a.EXAMEN_AULA_CODIGO = e.AULA_CODIGO
                 AND a.EXAMEN_SEDE_CODIGO = e.AULA_SEDE_CODIGO
              ) +
              (SELECT COUNT(*) FROM VIGILA v
               WHERE v.EXAMEN_FECHAYHORA  = e.FECHAYHORA
                 AND v.EXAMEN_AULA_CODIGO = e.AULA_CODIGO
                 AND v.EXAMEN_SEDE_CODIGO = e.AULA_SEDE_CODIGO
              ) > au.CAPACIDAD
          );
        RETURN V_CONTADOR = 0;
    END OCUPACION_OK;

    FUNCTION VOCAL_DUPLICADO(P_VOCAL_DNI VARCHAR2) RETURN BOOLEAN AS
        V_CONTADOR NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_CONTADOR
        FROM (
            SELECT EXAMEN_FECHAYHORA
            FROM VIGILA
            WHERE VOCAL_DNI = P_VOCAL_DNI
            GROUP BY EXAMEN_FECHAYHORA
            HAVING COUNT(*) > 1
        );
        RETURN V_CONTADOR > 0;
    END VOCAL_DUPLICADO;

    FUNCTION VOCALES_DUPLICADOS RETURN BOOLEAN AS
    BEGIN
        FOR v_vocal IN (SELECT DNI FROM VOCAL) LOOP
            IF VOCAL_DUPLICADO(v_vocal.DNI) THEN
                RETURN TRUE;
            END IF;
        END LOOP;
        RETURN FALSE;
    END VOCALES_DUPLICADOS;

    FUNCTION VOCAL_RATIO(P_RATIO NUMBER) RETURN BOOLEAN AS
        V_CONTADOR NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_CONTADOR
        FROM EXAMEN e
        WHERE e.FECHAYHORA > SYSDATE
          AND (
              (SELECT COUNT(*) FROM ASISTENCIA a
               WHERE a.EXAMEN_FECHAYHORA  = e.FECHAYHORA
                 AND a.EXAMEN_AULA_CODIGO = e.AULA_CODIGO
                 AND a.EXAMEN_SEDE_CODIGO = e.AULA_SEDE_CODIGO
              )
              >
              (SELECT COUNT(*) FROM VIGILA v
               WHERE v.EXAMEN_FECHAYHORA  = e.FECHAYHORA
                 AND v.EXAMEN_AULA_CODIGO = e.AULA_CODIGO
                 AND v.EXAMEN_SEDE_CODIGO = e.AULA_SEDE_CODIGO
              ) * P_RATIO
          );
        RETURN V_CONTADOR = 0;
    END VOCAL_RATIO;

END PK_OCUPACION;
/

-- 3. SEGURIDAD
-- PK_SEGURIDAD_PAU

-- CABECERA
CREATE OR REPLACE PACKAGE PK_SEGURIDAD_PAU AS
    PROCEDURE PR_CREA_ESTUDIANTE(P_DNI IN VARCHAR2, P_USUARIO OUT VARCHAR2, P_PASSWORD OUT VARCHAR2);
    PROCEDURE PR_CREA_VOCAL(P_DNI IN VARCHAR2, P_USUARIO OUT VARCHAR2, P_PASSWORD OUT VARCHAR2);
END PK_SEGURIDAD_PAU;
/

-- CUERPO
CREATE OR REPLACE PACKAGE BODY PK_SEGURIDAD_PAU AS

    PROCEDURE PR_CREA_ESTUDIANTE(P_DNI IN VARCHAR2, P_USUARIO OUT VARCHAR2, P_PASSWORD OUT VARCHAR2) AS
    BEGIN
        P_USUARIO  := 'EST_' || P_DNI;
        P_PASSWORD := DBMS_RANDOM.STRING('A', 10) || TRUNC(DBMS_RANDOM.VALUE(10,99));

        EXECUTE IMMEDIATE 'CREATE USER ' || P_USUARIO || ' IDENTIFIED BY "' || P_PASSWORD || '"';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.ASISTENCIA TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.EXAMEN TO ' || P_USUARIO;
    END PR_CREA_ESTUDIANTE;

    PROCEDURE PR_CREA_VOCAL(P_DNI IN VARCHAR2, P_USUARIO OUT VARCHAR2, P_PASSWORD OUT VARCHAR2) AS
    BEGIN
        P_USUARIO  := 'VOC_' || P_DNI;
        P_PASSWORD := DBMS_RANDOM.STRING('A', 10) || TRUNC(DBMS_RANDOM.VALUE(10,99));

        EXECUTE IMMEDIATE 'CREATE USER ' || P_USUARIO || ' IDENTIFIED BY "' || P_PASSWORD || '"';
        EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.EXAMEN TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.AULA TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.SEDE TO ' || P_USUARIO;
        EXECUTE IMMEDIATE 'GRANT SELECT ON PAU.VIGILA TO ' || P_USUARIO;
    END PR_CREA_VOCAL;

END PK_SEGURIDAD_PAU;
/

-- 4. TRIGGER
-- TR_BORRA_AULA

CREATE OR REPLACE TRIGGER TR_BORRA_AULA
BEFORE DELETE ON AULA
FOR EACH ROW
DECLARE
    V_CONTADOR NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CONTADOR
    FROM EXAMEN
    WHERE AULA_CODIGO      = :OLD.CODIGO
      AND AULA_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND FECHAYHORA < SYSDATE;

    IF V_CONTADOR > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede borrar: ya se han realizado examenes en esta aula');
    END IF;

    SELECT COUNT(*) INTO V_CONTADOR
    FROM EXAMEN
    WHERE AULA_CODIGO      = :OLD.CODIGO
      AND AULA_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND FECHAYHORA BETWEEN SYSDATE AND SYSDATE + 2;

    IF V_CONTADOR > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No se puede borrar: hay examenes en las proximas 48 horas');
    END IF;

    DELETE FROM VIGILA
    WHERE EXAMEN_AULA_CODIGO = :OLD.CODIGO
      AND EXAMEN_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND EXAMEN_FECHAYHORA  > SYSDATE;

    DELETE FROM ASISTENCIA
    WHERE EXAMEN_AULA_CODIGO = :OLD.CODIGO
      AND EXAMEN_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND EXAMEN_FECHAYHORA  > SYSDATE;

    DELETE FROM EXAMEN_ES_MATERIA
    WHERE EXAMEN_AULA_CODIGO = :OLD.CODIGO
      AND EXAMEN_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND EXAMEN_FECHAYHORA  > SYSDATE;

    DELETE FROM EXAMEN
    WHERE AULA_CODIGO      = :OLD.CODIGO
      AND AULA_SEDE_CODIGO = :OLD.SEDE_CODIGO
      AND FECHAYHORA       > SYSDATE;

END TR_BORRA_AULA;
/

-- 5. PROCEDIMIENTOS ADICIONALES
-- DESPISTE

CREATE OR REPLACE PROCEDURE DESPISTE(
    P_DNI   IN VARCHAR2,
    P_FECHA IN DATE,
    P_AULA  IN NUMBER,
    P_SEDE  IN NUMBER
) AS
    V_PRIMER_EXAMEN DATE;
BEGIN
    SELECT MIN(EXAMEN_FECHAYHORA) INTO V_PRIMER_EXAMEN
    FROM ASISTENCIA
    WHERE ESTUDIANTE_DNI  = P_DNI
      AND EXAMEN_FECHAYHORA BETWEEN SYSDATE AND SYSDATE + 1/24;

    IF V_PRIMER_EXAMEN IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'No queda menos de una hora para el primer examen del alumno');
    END IF;

    UPDATE ASISTENCIA
    SET EXAMEN_AULA_CODIGO = P_AULA,
        EXAMEN_SEDE_CODIGO = P_SEDE
    WHERE ESTUDIANTE_DNI    = P_DNI
      AND EXAMEN_FECHAYHORA = P_FECHA;

    FOR v_exam IN (
        SELECT EXAMEN_FECHAYHORA, MATERIA_CODIGO
        FROM ASISTENCIA
        WHERE ESTUDIANTE_DNI    = P_DNI
          AND EXAMEN_FECHAYHORA > P_FECHA
          AND TRUNC(EXAMEN_FECHAYHORA) = TRUNC(SYSDATE)
    ) LOOP
        DECLARE
            V_AULA_LIBRE NUMBER;
            V_SEDE_LIBRE NUMBER;
        BEGIN
            SELECT a.CODIGO, a.SEDE_CODIGO
            INTO V_AULA_LIBRE, V_SEDE_LIBRE
            FROM AULA a
            WHERE a.SEDE_CODIGO = P_SEDE
              AND NOT EXISTS (
                  SELECT 1 FROM ASISTENCIA ast
                  WHERE ast.EXAMEN_AULA_CODIGO = a.CODIGO
                    AND ast.EXAMEN_SEDE_CODIGO  = a.SEDE_CODIGO
                    AND ast.EXAMEN_FECHAYHORA   = v_exam.EXAMEN_FECHAYHORA
              )
            AND ROWNUM = 1;

            UPDATE ASISTENCIA
            SET EXAMEN_AULA_CODIGO = V_AULA_LIBRE,
                EXAMEN_SEDE_CODIGO = V_SEDE_LIBRE
            WHERE ESTUDIANTE_DNI    = P_DNI
              AND EXAMEN_FECHAYHORA = v_exam.EXAMEN_FECHAYHORA;

        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE_APPLICATION_ERROR(-20002,
                    'No hay aula libre en la sede ' || P_SEDE ||
                    ' para el examen del ' || v_exam.EXAMEN_FECHAYHORA);
        END;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Estudiante reubicado correctamente');

END DESPISTE;
/

-- MIGRAR_CENTRO

CREATE OR REPLACE PROCEDURE MIGRAR_CENTRO(
    P_CENTRO       IN NUMBER,
    P_SEDE_ORIGEN  IN NUMBER,
    P_SEDE_DESTINO IN NUMBER
) AS
    V_AULA_DESTINO NUMBER;
BEGIN
    FOR v_exam IN (
        SELECT DISTINCT a.EXAMEN_FECHAYHORA, a.EXAMEN_AULA_CODIGO
        FROM ASISTENCIA a
        JOIN ESTUDIANTE e ON e.DNI = a.ESTUDIANTE_DNI
        WHERE e.CENTRO_CODIGO      = P_CENTRO
          AND a.EXAMEN_SEDE_CODIGO = P_SEDE_ORIGEN
          AND a.EXAMEN_FECHAYHORA  > SYSDATE
    ) LOOP
        FOR v_alumno IN (
            SELECT a.ESTUDIANTE_DNI
            FROM ASISTENCIA a
            JOIN ESTUDIANTE e ON e.DNI = a.ESTUDIANTE_DNI
            WHERE e.CENTRO_CODIGO      = P_CENTRO
              AND a.EXAMEN_SEDE_CODIGO = P_SEDE_ORIGEN
              AND a.EXAMEN_FECHAYHORA  = v_exam.EXAMEN_FECHAYHORA
        ) LOOP
            BEGIN
                SELECT au.CODIGO INTO V_AULA_DESTINO
                FROM AULA au
                WHERE au.SEDE_CODIGO = P_SEDE_DESTINO
                  AND (
                      SELECT COUNT(*) FROM ASISTENCIA a2
                      WHERE a2.EXAMEN_AULA_CODIGO = au.CODIGO
                        AND a2.EXAMEN_SEDE_CODIGO  = P_SEDE_DESTINO
                        AND a2.EXAMEN_FECHAYHORA   = v_exam.EXAMEN_FECHAYHORA
                  ) < au.CAPACIDAD_EXAMEN
                AND ROWNUM = 1;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    ROLLBACK;
                    RAISE_APPLICATION_ERROR(-20001,
                        'No hay aulas disponibles en la sede destino ' || P_SEDE_DESTINO);
            END;

            UPDATE ASISTENCIA
            SET EXAMEN_SEDE_CODIGO = P_SEDE_DESTINO,
                EXAMEN_AULA_CODIGO = V_AULA_DESTINO
            WHERE ESTUDIANTE_DNI     = v_alumno.ESTUDIANTE_DNI
              AND EXAMEN_FECHAYHORA  = v_exam.EXAMEN_FECHAYHORA
              AND EXAMEN_SEDE_CODIGO = P_SEDE_ORIGEN;

        END LOOP;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Migracion completada correctamente');

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END MIGRAR_CENTRO;
/

COMMIT;